### ISSUE TITLE
Duplicate value on update for the array on scope.

### ISSUE THREAD

**Issue by victorsosa** [JohnnyTheTank/angular-bricklayer#7]
Hi,

If I updated the appendData in the $scope with a new array values, it won't update correctly the array and the items get always append to the array. In my case the array get updated every 30seg. So it will always present new duplicate values.

```
<div class="bricklayer" ng-cloak>
    <!-- append -->
    <div bricklayer-append ng-repeat="item in appendData" ng-cloak></div>

    <!-- prepend -->
    <div bricklayer-prepend ng-repeat="item in prependData" ng-cloak></div>
</div>
```

**Comment by JohnnyTheTank** [comment]
Could you show your problem in a plnkr like this? http://plnkr.co/edit/mo3G36

**Comment by victorsosa** [comment]
Hi,

Thanks for answer; here is the example http://plnkr.co/edit/AaS4UikE8E1sEMANidiq
In this example I call twice the restful service to setup the scope and you can see the data gets duplicated.

**Comment by JohnnyTheTank** [comment]
This is a typical angular ng-repeat problem. I fixed it here: http://plnkr.co/edit/2yMtGiQ5PIyJ1fvTbNVy

You should use the ng-repeat directive like this: `ng-repeat="item in data track by $index"`

**Comment by victorsosa** [comment]
Ok, got you point, can you try this version that use an interval to update?; It is exactly  like I have it in my code.

http://plnkr.co/edit/AaS4UikE8E1sEMANidiq

**Comment by JohnnyTheTank** [comment]
I fixed it here: http://plnkr.co/edit/9GPfHm29HZwhmzjfPtHS

the problem is, that you should'nt just replace the array by another array. You should just add or remove items of/to this array that you loop through `ng-repeat`

**Comment by victorsosa** [comment]
nice, but one more thing this only happens when I integrated with this component; because if I try without bricklayer everything works ok. Without the need of parse the array to check.

**Comment by JohnnyTheTank** [comment]
yes I know. 

> the problem is, that you should'nt just replace the array by another array. You should just add or remove items of/to this array that you loop through ng-repeat

this is the workaround for this component

**Comment by victorsosa** [comment]
You could use $watchCollection or $watch to reflect any change in the array. In this way it will be dynamic as expected.

https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watchCollection

**Comment by JohnnyTheTank** [comment]
can you open a PR for this? I have no time for this in the next months
